### ISSUE TITLE
RuntimeError: shape '[1, 1, 65864]' is invalid for input of size 131728

### ISSUE THREAD

**Issue by chikiuso** [shivammehta007/Neural-HMM#13]
Hi, I got the following error when run on cuda 11.2, do you have any hints how to solve it? thanks.

Traceback (most recent call last):
  File "generate_data_properties.py", line 179, in <module>
    main(args)
  File "generate_data_properties.py", line 147, in main
    data_mean, data_std, go_token_init_value, init_transition_prob = get_data_parameters_for_flat_start(
  File "generate_data_properties.py", line 78, in get_data_parameters_for_flat_start
    for i, batch in enumerate(tqdm(train_loader)):
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/Neural-HMM/src/utilities/data.py", line 166, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/root/Neural-HMM/src/utilities/data.py", line 126, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/root/Neural-HMM/src/utilities/data.py", line 148, in get_mel
    melspec = self.stft.mel_spectrogram(audio_norm)
  File "/root/Neural-HMM/src/model/layers.py", line 122, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "/root/Neural-HMM/src/utilities/stft.py", line 112, in transform
    input_data = input_data.view(num_batches, 1, num_samples)
RuntimeError: shape '[1, 1, 65864]' is invalid for input of size 131728

**Comment by shivammehta007** [comment]
Hello, 
This looks more like an Audio preprocessing bug, i.e when transforming data from raw waveform to mel-spectrograms. Could you please ensure that the `.wav` files that you are processing have the sample rate of `22050`?

**Comment by chikiuso** [comment]
thanks for your help!
